dataset:
  train:
    # path to extxyz files
    src: data/dataset1.extxyz
    # If we want to normalize each target value_ i.e. subtract the mean and
    # divide by standard deviation_ then those 'target_mean' and 'target_std'
    # statistics for energies and 'grad_target_mean' and 'grad_target_std'
    # statistics for forces need to be specified here for the train split.
    normalize_labels: True
  val:
    # path to extxyz files
    src: data/dataset2.extxyz
  test:
    # path to extxyz files
    src: data/dataset3.extxyz

kernel:
  alpha: 0.0 # Interpolate between w_0 and multi-weight regression
  aggregation: mean # To use mean or sum for the set-kernel
  k0:
    gaussian # base kernel `k` in paper
  k0_params: # Additional parameters passed to kernel object
    median_heuristic: True
  k1: # Outer kernel, fixed to be linear
    linear
  regressor_params: # Parameters passed to regression object
    lmbda: 1.0e-7
  representation_params: # Parameters used when extracting the GNN-feature map
    Representation_layer: 2
  model_checkpoint_path: checkpoints/s2ef_efwt/all/schnet/schnet_all_large.pt # Path to load model checkpoint

optim:
  # Coefficient to use for the force loss. Currently unused as we only train on energy
  force_loss_coefficient: 0.0

# Values for logger, such as tagging and name of run
logger:
  tags: []
  name: "mekrr-gauss-schnet"

task:
  train: True
  validate: ["val", "test"]
  predict: []

runner: "MEKRR"
